//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int Codigo { get; set; }
        public int ProdutoCod { get; set; }
        public int ProdutoQuant { get; set; }
        public Nullable<int> CliendCod { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
